name: Test Results

on:
  workflow_run:
    workflows: [ "Rust CI" ]
    types: [ completed ]

permissions: {}

jobs:
  test-results:
    name: Test Results
    if: ${{ github.event.workflow_run.event == 'pull_request' && (github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure') }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
      issues: read
      pull-requests: write
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          pattern: test-results-*
          path: artifacts/test-results

      - name: Download event file
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          name: event-file
          path: artifacts/event-file

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/event-file/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: artifacts/test-results/**/*.xml
          check_run: false
          job_summary: false
